services:
  silverbullet:
    build: ./
    init: true
    image: zefhemel/silverbullet
    container_name: silverbullet
    volumes:
      - space:/space
    ports:
      - ${PORT}:3000
volumes:
  space:
